### PR TITLE
feat!: Remove deprecated EC2 classic fields removed in AWS provider v5.0

### LINKED ISSUE #73: snapshot_copy does not work as per example
## Description

The `snapshot_copy` functionality does not work as per [examples/complete/main.tf](https://github.com/terraform-aws-modules/terraform-aws-redshift/blob/v4.0.2/examples/complete/main.tf) 

This does NOT work:
```terraform
  snapshot_copy = {
    useast1 = {
      destination_region = "us-east-1"
      grant_name         = aws_redshift_snapshot_copy_grant.useast1.snapshot_copy_grant_name
    }
  }
```

This works:
```terraform
  snapshot_copy = {
    destination_region = "us-east-1"
    grant_name         = aws_redshift_snapshot_copy_grant.useast1.snapshot_copy_grant_name
    retention_period   = 1
  }
```

Noticed this when upgrading from `v3.4.0` to `v4.0.2`
## Versions

- Module version [Required]: `v4.0.2`

- Terraform version:
`Terraform v1.0.11`
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.36.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

## Expected behavior

Snapshot copies to be configured

## Actual behavior

Existing snapshot copies are removed.

### Terminal Output Screenshot(s)

image

### LINKED ISSUE #85: Deprecation Error - Unsupported attribute "cluster_security_groups"
## Description

As EC2-Classic features have now been removed, when using the latest Terraform AWS Provider (v5.0.0 or later), the following error is reported when running a 'terraform validate:'

> Error: Unsupported attribute
> 
>   on .terraform/modules/redshift_standalone/outputs.tf line 71, in output "cluster_security_groups":
>   71:   value       = try(aws_redshift_cluster.this[0].cluster_security_groups, [])
> 
> This object has no argument, nested block, or exported attribute named "cluster_security_groups".

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

Issues [#81](https://github.com/terraform-aws-modules/terraform-aws-redshift/issues/81) and [#82](https://github.com/terraform-aws-modules/terraform-aws-redshift/issues/82) report these as deprecation warnings only (i.e. not show-stopping), but these now appear as full-blown errors. 

## Versions

- Module version: 4.0.3

- Terraform version: 1.4.6
- Provider version(s): 5.0.1

Run a `terraform validate`, `terraform plan` and/or `terraform apply`.

## Expected behavior

Successful execution without errors. 

## Actual behavior

Execute fails with `Error: Unsupported attribute`

### Terminal Output Screenshot(s)

> Error: Unsupported attribute
> 
>   on .terraform/modules/redshift_standalone/outputs.tf line 71, in output "cluster_security_groups":
>   71:   value       = try(aws_redshift_cluster.this[0].cluster_security_groups, [])
> 
> This object has no argument, nested block, or exported attribute named "cluster_security_groups".

### PR DESCRIPTION
**Pull request by matt-dancer-adwanted**
## Description

- Remove deprecated EC2 classic fields removed in AWS provider v5.0
- Raise AWS provider minimum supported version to v5.0
- Update and validate example

## Motivation and Context

- Resolves #73
- Resolves #84
- Resolves #85

## Breaking Changes
- Yes; provider minimum supported raised to v5.0 which removes the deprecated fields

### CODE REVIEW

**Comment by matt-dancer-adwanted** [comment]
I believe this relates to [https://github.com/hashicorp/terraform-provider-aws/issues/29480](https://github.com/hashicorp/terraform-provider-aws/issues/29480).

**Comment by brianpham** [comment]
Thanks for putting up a fix!

**Comment by brianpham** [comment]
@bryantbiggs Can you help review? Would love to have a fix so I don't need to pin my local AWS version

**Review by bryantbiggs — APPROVED** [review]
Thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 5.0.0 :tada:

**Pull request merged**
