### PR TITLE
Add tags to aws_redshift_parameter_group

### PR DESCRIPTION
**Pull request by idnorton**
# Description

Please explain the changes you made here and link to any relevant issues.

Add tags to the parameter group in the same way as other resources have this. No issue created, itentified the issue and fixed it in this PR.

### CODE REVIEW

**Comment by idnorton** [comment]
Adding an issue for the PR previously created.

**Comment by idnorton** [comment]
Fixes #21

**Comment by mohsen0** [comment]
Hi @antonbabenko Can you view this PR, it is a very simple one.

**Comment by mohsen0** [comment]
Hi @antonbabenko Can you view this PR, it is a very simple one.

**Comment by antonbabenko** [comment]
Thanks @idnorton !

[v2.3.0](https://github.com/terraform-aws-modules/terraform-aws-redshift/releases/v2.3.0) has been released with this feature.

**Pull request merged**
