### PR TITLE
[WIP] Add Redshift module

### PR DESCRIPTION
**Pull request by kwent**
Add Redshift module

### CODE REVIEW

**Comment by antonbabenko** [comment]
I guess this is WIP, because it does not look as similar to other verified modules as it should. Take a closer look into RDS module, for example.

**Comment by antonbabenko** [comment]
[v1.0.0](https://github.com/terraform-aws-modules/terraform-aws-redshift/releases/v1.0.0) is released. Please use this one to be forward-compatible with upcoming features (PRs are welcome, as usual).

**Comment by kwent** [comment]
@antonbabenko Thanks for the migration.

**Comment by antonbabenko** [comment]
You are welcome. Today was my first ever Redshift experience :)

**Pull request closed without merging**
